version: "3"

services:
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_DB=springbucks
      - POSTGRES_USER=springbucks
      - POSTGRES_PASSWORD=springbucks

  consul:
    image: consul
    expose:
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
      - 8600

  rabbitmq:
    image: rabbitmq:3.7-management
    expose:
      - 5672
      - 15672
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=spring
      - RABBITMQ_DEFAULT_PASS=spring

  zipkin:
    image: openzipkin/zipkin
    depends_on:
      - rabbitmq
    expose:
      - 9411
    ports:
      - 9411:9411
    links:
      - rabbitmq
    # Wait for rabbitmq - Can use wait-for-it instead.
    restart: always
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672 
      - RABBIT_USER=spring
      - RABBIT_PASSWORD=spring

  waiter-service:
    image: chenlehua/waiter-service:1.0-SNAPSHOT
    depends_on:
      - postgres
      - consul
      - rabbitmq
      - zipkin
    links:
      - postgres
      - consul
      - rabbitmq
      - zipkin
    expose:
      - 8080
    ports:
      - 8080:8080

  barista-service:
    image: chenlehua/barista-service:1.0-SNAPSHOT
    depends_on:
      - postgres
      - consul
      - rabbitmq
      - zipkin
    links:
      - postgres
      - consul
      - rabbitmq
      - zipkin

  customer-service-8090:
    image: chenlehua/customer-service:1.0-SNAPSHOT
    depends_on:
      - waiter-service
    links:
      - consul
      - rabbitmq
      - zipkin
      - waiter-service
    expose:
      - 8090
    ports:
      - 8090:8090
    environment:
      - SERVER_PORT=8090
